shared:
    image: node:18

jobs:
    X:
        requires: [~sd@12753:A]
        steps:
            - start: echo ok
    Y:
        requires: [~sd@12753:B]
        steps:
            - start: echo ok
