shared:
    image: node:18

jobs:
    sub:
        requires: [~sd@12753:main]
        steps:
            - start: echo ok
    sub2:
        requires: [~sd@12753:join]
        steps:
            - start: echo ok
